import {StyleSheet} from 'react-native'

export const style = StyleSheet.create({
 conteiner:{
     flex:1,
 },

 input:{
    height:50,
    marginBottom:12,
    width:320,
    marginTop:20,
    justifyContent:'center',
    alignItems: 'center',
    borderRadius:25.71,
    backgroundColor:"#fff"
 },
 ConteinerInput:{
     alignItems:'center',
     marginTop:70,
     width:'100%'
     
 },
 gradient:{
     flex:1,
     alignItems:'center',
     position:'relative',
     left:0,
     right:0,
     top:0,
 },
 conteinerGeo:{
     backgroundColor:'#fff',
     borderRadius:3,
     width:360,
     height:170,
     marginBottom:50,
     marginTop:30,
     justifyContent:'center',
     borderWidth:1,
     alignItems:'center',
     borderColor:'rgba(255, 255, 255, 0.9)',
 },
 text:{
     fontSize:20,
     marginLeft:4,
     marginTop:2,
     marginBottom:6,
     fontWeight:'bold',
     alignSelf:'flex-start',
     color:'#7A7A7A',
 },
 buttonGeo:{
   backgroundColor:'#9C07F2',
   height:50,
   width:280,
   marginTop:7,
   flexDirection:'row',
   justifyContent:'space-between',
   alignItems:'center',
   borderRadius:8,
   
 },
 textButtonGeo:{
     marginLeft: 45,
     color:'white',
     fontSize:18,
     fontWeight:'bold'
 },
 icon:{
  marginRight:50,
 },
 box:{
  height:100,
  marginTop:-30,
  width:'100%',
  flexDirection:'row',
  alignItems:'center',
  justifyContent:'space-between'
 },
 Save:{
  backgroundColor:'#5204DB',
  borderWidth:0.6,
  borderRadius:8,
  borderColor:'#fff',
  height:48,
  marginLeft:20,
  width:139,
  flexDirection:'row',
  textAlign:'center',
  alignItems:'center',
  justifyContent:'center'
 },
 Delete:{
  backgroundColor:'#CA2828',
  borderWidth:0.6,
  borderRadius:8,
  borderColor:'#fff',
  height:48,
  marginRight:20,
  width:139,
  textAlign:'center',
  alignItems:'center',
  justifyContent:'center'
 },
textBox:{
    marginRight:5,
    color:'#fff',
    fontSize:15,
    fontWeight:'bold',
    alignItems:'center'
    
},
Send:{
    borderWidth:2,
    display:'flex',
    borderColor:'#fff',
    backgroundColor:'#5204DB',
    borderRadius:15,
    height:59,
    width:87,
    left:0,
    right:0,
    top:-29,
    marginRight:39,
    alignSelf:'flex-end',
    justifyContent:'center',
    alignItems:'center',
    elevation:18,
    marginTop:80
 
}

});